Support setting image data from DirectByteBuffer
KhronosGroup/KTX-Software pull request #616
Opened 2022-08-11 04:03 UTC by westinrm

Allowing creation of KtxTexture from a DirectByteBuffer lets you interop with images written by other native libraries (for example, GDAL) without having to copy everything to and from the heap.

2022-08-11 04:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/KTX-Software?pullRequest=616) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/KTX-Software?pullRequest=616) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/KTX-Software?pullRequest=616) it.</sub>

2022-08-12 09:37 UTC, MarkCallow commented
I am on the verge of releasing 4.1.0, I will wait until that is done before reviewing and merging this.

Thank you for the contribution.

2022-08-30 09:59 UTC, MarkCallow requested changes
Looks good to me but I'm no Java expert anymore. It's a long time since I was making 3D graphics engines for J2ME.

Please strengthen the tests as indicated.

4.1.0 is still not released. I'm waiting for a new code signing certificate.

2022-08-30 09:59 UTC, MarkCallow commented on interface/java_binding/src/test/java/org/khronos/ktx/test/KtxTexture1Test.java
> +        texture.setImageFromBuffer(0, 0, 0, imageData);
You're not testing the result for KTX_SUCCESS.

2022-08-30 09:59 UTC, MarkCallow commented on interface/java_binding/src/test/java/org/khronos/ktx/test/KtxTexture1Test.java
> +        ByteBuffer imageData = ByteBuffer.allocateDirect(10 * 10);
I think you should put some known data in the ByteBuffer and after `setImageFromBuffer`, check that the texture has the expected data.

2022-08-30 09:59 UTC, MarkCallow commented on interface/java_binding/src/test/java/org/khronos/ktx/test/KtxTexture2Test.java
> +        ByteBuffer imageData = ByteBuffer.allocateDirect(10 * 10);
Same comment as for `texture1Test`.

2022-08-30 09:59 UTC, MarkCallow commented on interface/java_binding/src/test/java/org/khronos/ktx/test/KtxTexture2Test.java
> +        texture.setImageFromBuffer(0, 0, 0, imageData);
Same comment as for `texture1Test`.

2022-09-06 22:52 UTC, westinrm commented
I'm going to close this.  It's no longer useful to me and I won't have time to look at it for at least a month anyways.  I'll re-open if it becomes relevant again.

2022-09-06 22:52 UTC, closed without merging