Update KTX-Software-CTS reference to specific commit
KhronosGroup/KTX-Software pull request #731
Opened 2023-07-06 08:36 UTC by aqnuep

This PR only updates the submodule reference for the KTX-Software-CTS repository, as it should always refer to a specific commit to avoid new tests causing failures on old code.

@MarkCallow, could you please merge this in? Apparently this was overlooked when merging the KTX-Tools branch into main.

2023-07-06 13:45 UTC, VaderY approved these changes

2023-07-07 00:45 UTC, VaderY requested changes
I think this is fine as is because this is not the submodule ref and it refers to a different "branch" (the default remote branch, rarely used).

2023-07-07 01:38 UTC, MarkCallow commented
> I think this is fine as is because this is not the submodule ref and it refers to a different "branch" (the default remote branch, rarely used).

What is fine as is, this PR? What refers to the default remote branch, the commit hash in this update?

In general should KTX-Software's `main` point to the submodule's `main`? Then when a tag is added we need to ensure the submodule reference at that tag points at a specific commit?

How should we manage this from now on?

2023-07-07 01:39 UTC, MarkCallow reviewed
Please see my comment in the main conversation.

2023-07-07 02:18 UTC, VaderY commented
@MarkCallow By fine I mean I dont think there is an error in how we managed submodules so far, so this PR is not needed.

> In general should KTX-Software's `main` point to the submodule's `main`? Then when a tag is added we need to ensure the submodule reference at that tag points at a specific commit?

git submodule is managed on a per commit basis wish SHA. Each KTX commit references a CTS commit for it. So no need to do any extra work or synchronization beyond the normal development workflow

2023-07-07 06:46 UTC, aqnuep commented
Sorry, my bad. Indeed, @VaderY is right, that the branch specified in .gitsubmodule won't matter, as it is only used when you explicitly request the latest changes from the tracked branch to be pulled manually, hence this PR can be dropped.

2023-07-07 06:46 UTC, closed without merging