Color-space and documentation related improvements for ktx create
KhronosGroup/KTX-Software pull request #732
Opened 2023-07-07 09:05 UTC by VaderY

ktx create: Adding `none` as an --assign-primaries option (#725)
ktx create: Improving usage string and documentation (#726)
ktx create: Allow non-matching input file metadata with warnings (#728)

2023-07-07 10:03 UTC, MarkCallow requested changes
Looks good. I have 2 minor change requests.

2023-07-07 10:03 UTC, MarkCallow commented on tools/ktx/command_create.cpp
> +            fatal(rc::INVALID_FILE, "Input image \"{}\" has different transfer function ({}) than the first image ({}).",
On this and the error messages for gamma and primaries add a note to the message to the effect of "Use --assign-XXX or --convert-XXX to specify handling and stop this error."

2023-07-07 10:41 UTC, MarkCallow commented on tools/ktx/command_create.cpp
> +            the input files before the encoding step.
Please change "If the --encode option is used" to what you wrote in your response to issue #726. 

```
When used with --encode it specifies the format of your input files before the encoding step. In this case
it must be one of:
R8_UNORM
R8_SRGB
R8G8_UNORM
R8G8_SRGB
R8G8B8_UNORM
R8G8B8_SRGB
R8G8B8A8_UNORM
R8G8B8A8_SRGB
```

Then, after the sentence about ASTC,

```
The format will be used to verify and load all your input files into a texture before encoding.
```

2023-07-08 09:32 UTC, MarkCallow approved these changes

2023-07-08 09:34 UTC, merged

2023-07-08 09:35 UTC, MarkCallow commented
Thanks for the fixes.

2023-07-08 16:00 UTC, donmccurdy commented
Additions and clarifications look great to me as well – thank you!